USE [master]
GO

/****** Object:  Database [Library_Fedyaev]    Script Date: 24.01.2022 17:37:03 ******/
CREATE DATABASE [Library_Fedyaev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Library_Fedyaev', FILENAME = N'E:\SQL\MSSQL15.SQLEXPRESS\MSSQL\DATA\Library_Fedyaev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Library_Fedyaev_log', FILENAME = N'E:\SQL\MSSQL15.SQLEXPRESS\MSSQL\DATA\Library_Fedyaev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Library_Fedyaev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Library_Fedyaev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET ARITHABORT OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Library_Fedyaev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Library_Fedyaev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Library_Fedyaev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Library_Fedyaev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Library_Fedyaev] SET  MULTI_USER 
GO

ALTER DATABASE [Library_Fedyaev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Library_Fedyaev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Library_Fedyaev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Library_Fedyaev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Library_Fedyaev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Library_Fedyaev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Library_Fedyaev] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Library_Fedyaev] SET  READ_WRITE 
GO


